// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetPost(ctx context.Context, id string) (Post, error)
	GetResetKey(ctx context.Context, username string) (Verification, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetVerifyKey(ctx context.Context, username string) (Verification, error)
	GetverificationStatus(ctx context.Context, username string) (sql.NullBool, error)
	ListPosts(ctx context.Context) ([]Post, error)
	SetResetKeyAndState(ctx context.Context, arg SetResetKeyAndStateParams) error
	SetVeriftyStatues(ctx context.Context, arg SetVeriftyStatuesParams) error
	SetVerifyCode(ctx context.Context, arg SetVerifyCodeParams) error
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
}

var _ Querier = (*Queries)(nil)
